require_relative './cinema/money_helper'
require_relative './cinema/cashbox'
require_relative './cinema/movie'
require_relative './cinema/moviecollection'
require_relative './cinema/netflix'
require_relative './cinema/theatre'
