require_relative './cinema/cashbox_implementation.rb'
require_relative './cinema/movie'
require_relative './cinema/moviecollection'
require_relative './cinema/netflix'
require_relative './cinema/theatre'
